package com.healthcare.demo.service;

import java.util.ArrayList;
import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.healthcare.demo.model.DiseaseModel;
import com.healthcare.demo.repository.DiseaseRepository;
import com.healthcare.demo.service.DiseaseService;

@Service
public class DiseaseServiceImpl implements DiseaseService {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private DiseaseRepository diseaseRepository;

   
	@Override
	public List<DiseaseModel> findAll() {
		List<DiseaseModel> list = new ArrayList<>();
		diseaseRepository.findAll().iterator().forEachRemaining(list::add);
		return list;
	}
    
    
	@Override
	public void addDisease(DiseaseModel diseasemodel) {
		diseaseRepository.save(diseasemodel);
    }
    
	@Override
	public List<DiseaseModel> findById(int id) {
		return diseaseRepository.findById(id);
	}
	@Override
	public void deleteById(int id) {
		diseaseRepository.deleteById(id);
	}
	@Override
	public DiseaseModel updateById(int id, DiseaseModel update) {
		return diseaseRepository.updateById(id, update);
	}
	@Override
	public List<DiseaseModel> findByDiseaseNameContaining(String diseaseName) {
		return diseaseRepository.findByDiseaseNameContaining(diseaseName);
	}
}
