package com.healthcare.demo.service;

import java.util.ArrayList;
import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.healthcare.demo.model.MedicalRecordModel;
import com.healthcare.demo.repository.MedicalRecordRepository;
import com.healthcare.demo.service.MedicalRecordService;

@Service
public class MedicalRecordServiceImpl implements MedicalRecordService {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private MedicalRecordRepository medicalRecordRepository;

   
	@Override
	public List<MedicalRecordModel> findAll() {
		List<MedicalRecordModel> list = new ArrayList<>();
		medicalRecordRepository.findAll().iterator().forEachRemaining(list::add);
		return list;
	}
    
    
	@Override
	public void addMedicalRecord(MedicalRecordModel medicalRecordModel) {
		medicalRecordRepository.save(medicalRecordModel);
    }
    
	@Override
	public MedicalRecordModel findById(int id) {
		return medicalRecordRepository.findById(id);
	}
	@Override
	public void deleteById(int id) {
		MedicalRecordModel model = medicalRecordRepository.findById(id);
		model.setIsArchived(true);
		medicalRecordRepository.save(model);
	}
	@Override
	public void restoreById(int id) {
		MedicalRecordModel model = medicalRecordRepository.findById(id);
		model.setIsArchived(false);
		medicalRecordRepository.save(model);
	}
	@Override
	public MedicalRecordModel updateById(int id, MedicalRecordModel update) {
		return medicalRecordRepository.updateById(id, update);
	}
}
